### ISSUE TITLE
Unable to detect any peripheral after stopping stream

### ISSUE THREAD

**Issue by mistertoze** [l1m3r/freeVHUSB4SL#1]
Hello,

I encountered an issue when using freeVHUSB4SL.

When choosing "Stop Streaming", the system returns to the Steam Link main menu and when it starts connecting to the network, it immediately shows the "insert a controller" warning ([image](https://www.howtogeek.com/wp-content/uploads/2018/02/ximg_5a8cb3074acc2.jpg.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.HWa66jEvVm.jpg)).

Unplugging and plugging the controller does nothing.

And unplugging the controller before the Steam Link restarts also does nothing.

It won't work unless I shutdown the Steam Link by pulling the cord.

Are you still working on this? Do you think you can fix it?

Thank you.

**Comment by l1m3r** [comment]
I never encountered this problem but I think this is - in a way - by design.

My guess is only one controller (be it mouse/keyboard/etc.) is connected to your SLink and you forward this controller to your computer.

Now as long as
1. the VHUSB client is running on your computer,
2. the VHUSB daemon/server is running on the SLink
3. and both are connected to the same network
the USB device you choose to forward will stay forwarded as long as all three conditions are met and thus remain hidden/disconnected from/to the SLink OS.

You need to close the client, tell it to stop 'grabbing' the controller from the SLink or powercycle the SLink to stop the server/daemon.

~~I'll add that information as soon as I~~ transfer my main post about his on the steam forums here (into the readme.md I think).
The information about this general behavior is already in the original post - I'll just point it out more emphatically.


Take a look at my first post in the fVHusb thread on the [steam forums](http://steamcommunity.com/app/353380/discussions/1/2549465882922214788/#c2549465882922304747) for a possible solution.
(I need to upload my version of that script some time...)

**Comment by mistertoze** [comment]
I can confirm that closing the VHUSB server before choosing "Stop Streaming" solves the issue.

I guess I'll create a key combination or something to kill the server from the gamepad.

On a related note, when using a script like the "AHK Desktop Streaming", do you know of a way to keep Big Picture from focusing on the VHUSB server window? I really just wanted the program to start without Steam thinking it was a game.

Thanks.
